version: '3'
services:
  app:
    build: .
    image: laravel-secret-friend-app
    container_name: secret-friend-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3001:80
      - 5173:5173
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./data:/var/lib/mysql
    ports:  
      - 3306:3306
  db-test:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./data-test:/var/lib/mysql
    ports:
      - 33060:3306
