version: '3.8'
services:
    app:
        build: .
        image: secret-friend-app
        container_name: secret-friend-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: secret-friend-nginx
        ports:
            - "3001:80"
        volumes:
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
            - .:/var/www
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app-network

    db-test:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - ./data-test:/var/lib/mysql
        ports:
            - 33060:3306
        networks:
            - app-network

networks:
  app-network:
    driver: bridge
