version: '3'
services:
  app:
    build: .
    image: laravel-secret-friend-app
    ports:
      - 3001:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - ./data:/var/lib/mysql
